# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.network "private_network", ip: "10.0.0.52"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "object2"
    vb.memory = "2048"

    dataDisk1 = './dataDisk1.vdi'
    dataDisk2 = './dataDisk2.vdi'

    if not File.exists?(dataDisk1)
      vb.customize ['createhd', '--filename', dataDisk1, '--variant', 'Fixed', '--size', 5 * 1024]
    end

    if not File.exists?(dataDisk2)
      vb.customize ['createhd', '--filename', dataDisk2, '--variant', 'Fixed', '--size', 5 * 1024]
    end

    vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--add', 'sata', '--portcount', 4]

    # Attaching the disks using the SATA controller
    vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', dataDisk1]
    vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', dataDisk2]

  end

  #config.vm.provision "shell", inline: <<-SHELL
  #  sudo mkfs.ext4 /dev/sdb
  #  sudo mkfs.ext4 /dev/sdc
  #SHELL

  config.vm.provision "shell", path: "init.sh"
end
